---
title: Analysis of CSV File Reading in R
date: STAT 407 Fall 2021
output: 
  beamer_presentation: 
    theme: Boadilla
    color: beaver
    fonttheme: professionalfonts
    keep_tex: yes
    df_print: kable
    highlight: tango
csl: apa.csl
bibliography: ref.bib
# aspectratio: 169
fontsize: 11pt
header-includes:
  - \usepackage{xcolor}
  - \definecolor{luc}{RGB}{88, 41, 49}
  - \setbeamercolor{itemize/enumerate body}{fg=luc}
  - \setbeamercolor{title}{fg=luc}
  - \setbeamercolor{frametitle}{fg=luc}
  - \setbeamertemplate{itemize item}{\color{luc}$\blacktriangleright$}
  - \setbeamertemplate{itemize subitem}{\color{luc}$\blacktriangleright$}
  - \setbeamercolor{footnote}{fg=luc}
  - \setbeamercolor{footnote mark}{fg=luc}
  - \setbeamercolor{footlinecolor}{fg=black,bg=lightgray}
  - \setbeamertemplate{navigation symbols}{}
  - \author[Q. Nguyen \& R. Tedesco]{Quang Nguyen* and Robert Tedesco*}
  - \institute[]{* Loyola University Chicago}
  - \setbeamercovered{transparent}
  - \setbeamercolor{block title}{fg=luc}
  - \setbeamercolor{local structure}{fg=luc}
  - \usepackage{bbding}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "")
```

#   Outline

*   Background

*   Design and Data

*   ANOVA

*   Additional Analysis

*   Discussion

#   Background

*   Statisticians struggle with reading in large dataset [@gregcsv]

*   `read.csv`, part of `base` `R` [@baser], is old and slow.

*   Old dogs need to learn new tricks

*   There are better and more efficient data I/O algorithms in `R` [@efficient]

    *   `rio::import` [@rio]
    
    *   `readr::read_csv` [@readr] - part of `tidyverse` [@tidyverse]
    
    *   `data.table::fread` [@datatable]
    
#   Objective

Our goal is to design an experiment...

#   Design

*   $3^k$ factorial design [@montgomery]

*   $n = 20$ replicates

*   How were the data generated?

#   ANOVA

*   Insert table

*   Post-hoc

#   Additional Analysis

*   don't know yet

#   Discussion

*   Take advantage of more efficient algorithms.

#   Cheers.

*   S/o out Drs. Perry and Matthews

*   Greg's YouTube video: [youtu.be/E5KJkooW4RY](https://youtu.be/E5KJkooW4RY)

*   GitHub: [github.com/qntkhvn/read_speed](https://github.com/qntkhvn/read_speed)

*   Question?  

# References {.allowframebreaks}